# Decision Tree

#### checkout 1 - basic
https://www.youtube.com/watch?v=JcI5E2Ng6r4

#### checkout 2 - Entropy & IG
https://www.youtube.com/watch?v=YtebGVx-Fxw&t=388s

#### Finally 
https://www.youtube.com/watch?v=NxEHSAfFlK8&t=592s

#### Some key method to checkout


##### Python conditional expression

"var_name = success_value if actual_condition_expression else failure_value"

In [3]:
#Counter class - most_common function 

import numpy as np
from collections import Counter

a1 = np.array([1,2,2,2,1,3,4])

r1 =Counter(a1).most_common(2) # n - no of common elements.
print(r1)

[(2, 3), (1, 2)]


In [3]:
np.random.choice(a1, size=3, replace=False) # Get random element from given a1 and size of result, don't duplicate if replace=False

array([1, 2, 2])

In [4]:
np.random.choice(5, size=3, replace=False) # here a1 is np.arrange(5)

array([1, 0, 3])

In [5]:
a2 = np.array([1,2,2,2,3,4,3,3,3,3,3,6])
np.bincount(a2) 

# result- array([0, 1, 3, 6, 1, 0, 1])
# it say number 1 is 0, 1 is 1 time, 2 is 3times, 3 is 6times, etc..
# check it - https://numpy.org/doc/stable/reference/generated/numpy.bincount.html

array([0, 1, 3, 6, 1, 0, 1])

In [6]:
# Extra ;)
x = np.array([5, 1, 1, 2, 2, 2,5])
np.bincount(x)

array([0, 2, 3, 0, 0, 2])

In [7]:
w= np.array([0.3, 0.5, 0.2, 0.7, 1., -0.6,3])
np.bincount(x, weights=w)

array([0. , 0.7, 1.1, 0. , 0. , 3.3])

In [8]:
a2 = np.array([1,2,2,2,3,4,3,3,3,3,3,6])
b = np.bincount(a2) 

len(b/2)


7

In [9]:
a2,np.argwhere(a2<3)

(array([1, 2, 2, 2, 3, 4, 3, 3, 3, 3, 3, 6]),
 array([[0],
        [1],
        [2],
        [3]]))

In [10]:
py = np.array([5,5,5,2,2,2,3,3,3,3]) # mixed label - 5,2,3

def entropy (y):
    hist = np.bincount(y)
    ps = hist / len(y)
    return -np.sum([p * np.log(p) for p in ps if p>0])

In [11]:
entropy(py) # - E - 1.088 since mixed labels

1.0888999753452238

In [12]:
ly = np.array([5,5,5])

ry = np.array([2,2,2,3,3,3,3])

In [13]:
entropy(ly),entropy(ry) # -ly - 0 since no mixed info but ry - high mixed info

(-0.0, 0.6829081047004717)

In [14]:
ly = np.array([2,2,2,3,3])

ry = np.array([5,5,5,3,3])

In [15]:
entropy(ly), entropy(ry)

(0.6730116670092565, 0.6730116670092565)

In [20]:
np.log2(0) # remember to skip feeding zero value to log

/var/folders/5j/v43m74mn4b781ybkkx__t97h0000gr/T/ipykernel_924/2251961259.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(0)


-inf

In [21]:
0/10

0.0

In [24]:
ly[ly>2]

array([3, 3])

In [10]:
s = np.arange(10)
r =s.reshape(5,2)
r

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
np.swapaxes(r, 0,1)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])